---

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: conda_ubi8
    image: registry.access.redhat.com/ubi8/ubi
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
verifier:
  name: ansible
  directory: ../shared/tests/
...
