---

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: conda_centos8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
verifier:
  name: ansible
  directory: ../shared/tests/
...
