---
dependency:
  name: galaxy
driver:
  name: azure
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
    destroy: destroy.yml
verifier:
  name: ansible
  directory: ../shared/tests/
